---
title: "Empirical Analysis of AMZN Microstructure Data"
author: "Sid Bhatia"
date: "12/3/2023"
output: pdf_document
---

## Importation

Import the required libraries.

```{r}
library(highfrequency)
library(tidyverse)
library(xts)
library(lubridate)
```

## Data Pre-Processing

Load and pre-process the TAQ data.

```{r}
# Write file path for data.
file_path <- 'C://Users//sbhatia2//OneDrive - stevens.edu//Desktop//amzn_tick_history_01_04_2023.csv'

# Read in TAQ data.
data <- read.csv(file_path)

head(data)
tail(data)

# Display columns of dataset.
colnames(data)

head(data$Bid.Price)
tail(data$Bid.Price)

head(data$Ask.Price)
tail(data$Ask.Price)

# Remove rows with NA Bid/Ask/Trade prices.
cleaned_data <- data[!is.na(data$Bid.Price) & !is.na(data$Ask.Price) & !is.na(data$Price), ]

head(cleaned_data)
tail(cleaned_data)
```

## Liquidity Analysis

#### Price Computation

```{r}
# Determine number of trades in dataset.
num_of_trades <- nrow(cleaned_data)

paste("Total number of trades for AMZN on 01/04/2023:", num_of_trades)

# Retrieve trade, bid, and ask prices.
prices <- as.numeric(cleaned_data$Price)
bids <- as.numeric(cleaned_data$Bid.Price)
asks <- as.numeric(cleaned_data$Ask.Price)

# Compute the mid price as the average of the bid and ask prices.
mids <- (bids + asks) * 0.5
```

#### Trade vs. Mid Price Plotting

```{r}
```